In [1]:
import torch
from torch.utils.data import Dataset
import pandas as pd
import cv2
from tqdm import tqdm
import numpy as np

class CASMECombinedDataset(Dataset):
    def __init__(self,path = '.',
                 img_sz = 128,
                 calculate_strain = False,
                 initialized_df = None):
        
        if initialized_df is None:
            print('Initializing CASME Combined Dataset...')
            self.df = pd.read_csv(path + '/' + 'combined_all_classes.csv')
            self.df['OpticalFlow'] = None
            self.path = path
            self.img_sz = img_sz
            for idx,row in tqdm(self.df.iterrows(),ascii = '='):
                prefix = self.__get_prefix(row)
                onset = self.__read_img(
                    prefix + str(row['Onset']) + '.jpg'
                )
                apex = self.__read_img(
                    prefix + str(row['Apex']) + '.jpg'
                )
                self.df.at[idx,'OpticalFlow'] = self.__calc_optical_flow(onset,apex)
                if calculate_strain:
                    self.df.at[idx,'OpticalFlow'] = self.__append_optical_strain(self.df.at[idx,'OpticalFlow'])
                self.df.at[idx,'Class'] = {'anger':0,'disgust':1,'fear':2,'happiness':3,'repression':4,'sadness':5,'surprise':6}[row['Class']]  
        else:
            self.df = initialized_df
    
    def __get_prefix(self,row):
        sub_sample = row['Subject'] + '/' + row['Sample'] + '/'
        if row['Dataset'] == 'casme1':
            return self.path + '/casme1_cropped/' + sub_sample + 'reg_' + row['Sample'] + '-'
        elif row['Dataset'] == 'casme2':
            return self.path + '/casme2_cropped/' + sub_sample + 'reg_img'
        elif row['Dataset'] == 'casme^2':
            return self.path + '/casme^2_cropped/' + sub_sample + 'img'
            
    def __read_img(self,name):
        return cv2.cvtColor(
            cv2.resize(
                cv2.imread(name,cv2.IMREAD_COLOR),
                (self.img_sz,self.img_sz),
                interpolation = cv2.INTER_CUBIC
            ),
            cv2.COLOR_BGR2GRAY
        )
    
    def __calc_optical_flow(self,onset,apex):
        return np.array(
            cv2.optflow.DualTVL1OpticalFlow_create().calc(onset,apex,None)
        ).transpose((2,0,1))
    
    def __append_optical_strain(self,flow):
        ux = cv2.Sobel(flow[0],cv2.CV_32F,1,0)
        uy = cv2.Sobel(flow[0],cv2.CV_32F,0,1)
        vx = cv2.Sobel(flow[1],cv2.CV_32F,1,0)
        vy = cv2.Sobel(flow[1],cv2.CV_32F,0,1)
        strain = np.sqrt(ux * ux + uy * uy + 0.5 * (vx + uy) * (vx + uy))
        return np.concatenate((flow,strain.reshape(1,self.img_sz,self.img_sz)),axis = 0)
        
    def __len__(self):
        return len(self.df)
    
    def __getitem__(self,idx):
        return self.df.at[idx,'OpticalFlow'],int(self.df.at[idx,'Class'])
        
class LOSOGenerator():
    def __init__(self,dataset):
        self.data = dataset
        self.subjects = self.data.df[['Dataset','Subject']].drop_duplicates().reset_index()
        self.idx = 0
    
    def __iter__(self):
        return self
    
    def __next__(self):
        if self.idx == len(self.subjects):
            raise StopIteration
        ds,sub = self.subjects.at[self.idx,'Dataset'],self.subjects.at[self.idx,'Subject']
        self.idx += 1
        train_df = self.data.df[(self.data.df.Dataset != ds) | (self.data.df.Subject != sub)] \
            .reset_index(drop=True)
        test_df = self.data.df[(self.data.df.Dataset == ds) & (self.data.df.Subject == sub)] \
            .reset_index(drop=True)
        return CASMECombinedDataset(initialized_df = train_df),CASMECombinedDataset(initialized_df = test_df)

In [2]:
from torch import nn
import torch

class SingleStream(nn.Module):
    def __init__(self,out_c):
        super(SingleStream,self).__init__()
        self.conv = nn.Conv2d(in_channels = 3,out_channels = out_c,kernel_size = 3,padding = 1)
        self.pool = nn.MaxPool2d(kernel_size = 3,stride = 3,padding = 1)
    
    def forward(self,x):
        x = self.conv(x)
        x = self.pool(x)
        return x

class STSTNet2(nn.Module):
    def __init__(self):
        super(STSTNet2,self).__init__()
        self.stream1 = SingleStream(3)
        self.stream2 = SingleStream(5)
        self.stream3 = SingleStream(8)
        self.pool = nn.MaxPool2d(kernel_size = 2,stride = 2)
        self.dense = nn.Sequential(
            nn.Linear(400,400),
            nn.Dropout(0,8),
            nn.ReLU(),
            nn.Linear(400,7)
        )

    def forward(self,x):
        x1 = self.stream1(x)
        x2 = self.stream2(x)
        x3 = self.stream3(x)
        x = torch.cat([x1,x2,x3],dim = 1)
        x = self.pool(x)
        x = x.view(-1,400)
        x = self.dense(x)
        return x

In [3]:
ststf = torch.load('maml_ststnet.pth',map_location = torch.device('cpu'))

/home/qwq/anaconda3/lib/python3.8/site-packages/torch/serialization.py:658: SourceChangeWarning: source code of class 'torch.nn.modules.container.ParameterList' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/home/qwq/anaconda3/lib/python3.8/site-packages/torch/nn/modules/container.py:434: UserWarning: Setting attributes on ParameterList is not supported.
  warnings.warn("Setting attributes on ParameterList is not supported.")


In [4]:
model = STSTNet2()

In [5]:
ststf

STSTNet(
  (vars): ParameterList(
      (0): Parameter containing: [torch.FloatTensor of size 3x3x3x3]
      (1): Parameter containing: [torch.FloatTensor of size 3]
      (2): Parameter containing: [torch.FloatTensor of size 5x3x3x3]
      (3): Parameter containing: [torch.FloatTensor of size 5]
      (4): Parameter containing: [torch.FloatTensor of size 8x3x3x3]
      (5): Parameter containing: [torch.FloatTensor of size 8]
      (6): Parameter containing: [torch.FloatTensor of size 400x400]
      (7): Parameter containing: [torch.FloatTensor of size 400]
      (8): Parameter containing: [torch.FloatTensor of size 5x400]
      (9): Parameter containing: [torch.FloatTensor of size 5]
  )
)

In [6]:
conv1 = model.stream1.conv.state_dict()
conv1['weight'] = ststf.vars[0]
conv1['bias'] = ststf.vars[1]
model.stream1.conv.load_state_dict(conv1)
conv2 = model.stream2.conv.state_dict()
conv2['weight'] = ststf.vars[2]
conv2['bias'] = ststf.vars[3]
model.stream2.conv.load_state_dict(conv2)
conv3 = model.stream3.conv.state_dict()
conv3['weight'] = ststf.vars[4]
conv3['bias'] = ststf.vars[5]
model.stream3.conv.load_state_dict(conv3)
fc1 = model.dense[0].state_dict()
conv3['weight'] = ststf.vars[6]
conv3['bias'] = ststf.vars[7]
model.dense[0].load_state_dict(fc1)

<All keys matched successfully>

In [7]:
import torch.nn.functional as F

class focal_loss(nn.Module):
    def __init__(self, alpha=0.25, gamma=2, num_classes = 7, size_average=True):
        super(focal_loss,self).__init__()
        self.size_average = size_average
        if isinstance(alpha,list):
            assert len(alpha)==num_classes   
            self.alpha = torch.Tensor(alpha)
        else:
            assert alpha<1  
            self.alpha = torch.zeros(num_classes)
            self.alpha[0] += alpha
            self.alpha[1:] += (1-alpha)

        self.gamma = gamma

    def forward(self, preds, labels):
        # assert preds.dim()==2 and labels.dim()==1
        preds = preds.view(-1,preds.size(-1))
        self.alpha = self.alpha.to(preds.device)
        preds_softmax = F.softmax(preds, dim=1) 
        preds_logsoft = torch.log(preds_softmax)
        
        #focal_loss func, Loss = -α(1-yi)**γ *ce_loss(xi,yi)
        preds_softmax = preds_softmax.gather(1,labels.view(-1,1)) 
        preds_logsoft = preds_logsoft.gather(1,labels.view(-1,1))
        self.alpha = self.alpha.gather(0,labels.view(-1))
        # torch.pow((1-preds_softmax), self.gamma) 为focal loss中 (1-pt)**γ
        loss = -torch.mul(torch.pow((1-preds_softmax), self.gamma), preds_logsoft) 

        loss = torch.mul(self.alpha, loss.t())
        if self.size_average:
            loss = loss.mean()
        else:
            loss = loss.sum()
        return loss


In [8]:
import torch
from tqdm.notebook import tqdm
import numpy as np
from torch.utils.data import DataLoader
from torch import nn,optim
import pickle as pkl
from sklearn.metrics import recall_score,f1_score
from copy import deepcopy

from_file = 1
dataset = None
data_filename = 'dataset28x28_allclass_strain.pkl'
print_debug_info = 1
n_epochs = 200
device = torch.device('cpu')
observed_epochs = set([i for i in range(0,n_epochs,20)])

if from_file:
    with open(data_filename,'rb') as f:
        dataset = pkl.load(f) 
else:    
    dataset = CASMECombinedDataset(path = '/home/qwq/MAML-MER/dataset',img_sz = 28,calculate_strain = 1)
    with open(data_filename,'wb') as f:
        pkl.dump(dataset,f)

def train(trainset,testset):
    loader = DataLoader(trainset,batch_size = len(trainset),shuffle = True)
    model0 = deepcopy(model)
    model0.train()
    optimizer = optim.Adam(model0.parameters(),lr = 1e-3)
    criterion = nn.CrossEntropyLoss(weight = torch.Tensor([10,1,10,2,2,10,2])).to(device)
    res_dict = {}
    for epoch in tqdm(range(n_epochs)):
        losses = []
        for idx,(x,y) in enumerate(loader):
            x,y = x.to(device),y.to(device)
            out = model0(x)
            loss = criterion(out,y)
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
            losses.append(loss.cpu().detach().numpy())
        if epoch in observed_epochs:
            res = test(model0,testset)
            res_dict[epoch] = res
            model0.train()
            if print_debug_info:
                print('Epoch ' + str(epoch))
                print(np.mean(np.array(losses)))
                print(res)
            
    return res_dict
    
def test(model0,testset):
    loader = DataLoader(testset,batch_size = 1,shuffle = True)
    model0.eval()
    y,pred = [],[]
    for idx,(x0,y0) in enumerate(loader):
        x0,y0 = torch.Tensor(x0).to(device),y0.numpy()
        y.append(y0[0])
        pred0 = model0(x0).cpu().detach().numpy()
        pred.append(np.where(pred0[0] == np.max(pred0[0]))[0][0])
    y,pred = np.array(y),np.array(pred)
    print(y,pred)
    return get_metric(y,pred)

def get_metric(y,pred):
    uar = recall_score(y,pred,average = 'macro')
    uf1 = f1_score(y,pred,average = 'macro')
    return uar,uf1

def loso():
    print('Start cross validation.')
    results = []
    for idx,(trainset,testset) in tqdm(enumerate(LOSOGenerator(dataset))):
        print('Test ' + str(idx))
        res = train(trainset,testset)
        results.append(res)
        e1,(max_uar,_) = sorted(list(res.items()),reverse = True,key = lambda x:x[1][0])[0]
        e2,(_,max_uf1) = sorted(list(res.items()),reverse = True,key = lambda x:x[1][1])[0]
        print('Max UAR:' + str(max_uar) + ' at epoch ' + str(e1))
        print('Max UF1:' + str(max_uf1) + ' at epoch ' + str(e2))
    
    print('Cross validation finished.')
    mean_uar = lambda epoch:np.mean(np.array([dic[epoch][0] for dic in results]))
    mean_uf1 = lambda epoch:np.mean(np.array([dic[epoch][1] for dic in results]))
    e1 = sorted(list(observed_epochs),reverse = True,key = mean_uar)[0]
    max_mean_uar = mean_uar(e1)
    e2 = sorted(list(observed_epochs),reverse = True,key = mean_uar)[0]
    max_mean_uf1 = mean_uf1(e2)
    print('Max mean UAR:' + str(max_mean_uar) + ' at epoch ' + str(e1))
    print('Max mean UF1:' + str(max_mean_uf1) + ' at epoch ' + str(e2))
    
    with open(train_process_filename,'wb') as f:
        pkl.dump(results,f)
    
if __name__=='__main__':
    loso()

Start cross validation.


Test 0


/home/qwq/anaconda3/lib/python3.8/site-packages/torch/autograd/__init__.py:130: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
  Variable._execution_engine.run_backward(
/home/qwq/anaconda3/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1221: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


[1 0 3] [4 4 4]
Epoch 0
1.9523461
(0.0, 0.0)
[0 3 1] [4 1 5]
Epoch 20
1.0763148
(0.0, 0.0)
[1 0 3] [1 1 3]
Epoch 40
0.6217654
(0.6666666666666666, 0.5555555555555555)
[0 3 1] [1 3 3]
Epoch 60
0.3608204
(0.3333333333333333, 0.2222222222222222)
[3 0 1] [3 1 3]
Epoch 80
0.20806886
(0.3333333333333333, 0.2222222222222222)
[1 3 0] [1 3 1]
Epoch 100
0.121324636
(0.6666666666666666, 0.5555555555555555)
[1 0 3] [1 1 3]
Epoch 120
0.07338748
(0.6666666666666666, 0.5555555555555555)
[3 0 1] [1 1 1]
Epoch 140
0.04544264
(0.3333333333333333, 0.16666666666666666)
[3 1 0] [1 1 1]
Epoch 160
0.029074276
(0.3333333333333333, 0.16666666666666666)
[1 0 3] [1 1 1]
Epoch 180
0.019534722
(0.3333333333333333, 0.16666666666666666)

Max UAR:0.6666666666666666 at epoch 40
Max UF1:0.5555555555555555 at epoch 40
Test 1


[3 1 1 3 3 3 3 6] [4 4 4 4 4 6 1 4]
Epoch 0
1.953066
(0.0, 0.0)
[3 3 3 1 6 3 3 1] [4 1 0 1 5 0 4 6]
Epoch 20
1.0693387
(0.08333333333333333, 0.08333333333333333)
[3 3 6 3 1 3 1 3] [0 6 2 1 6 3 1 1]
Epoch 40
0.6097471
(0.13999999999999999, 0.14666666666666667)
[3 3 3 1 6 3 3 1] [6 1 1 1 2 6 3 6]
Epoch 60
0.3511306
(0.175, 0.18333333333333335)
[3 6 3 3 3 1 3 1] [3 2 6 1 6 6 1 1]
Epoch 80
0.20397268
(0.175, 0.18333333333333335)
[3 3 3 3 3 1 6 1] [6 1 6 1 3 6 2 1]
Epoch 100
0.120171286
(0.175, 0.18333333333333335)
[3 3 3 1 3 1 6 3] [1 3 6 1 6 6 2 1]
Epoch 120
0.073312216
(0.175, 0.18333333333333335)
[3 3 6 3 3 1 3 1] [6 6 2 1 1 1 3 6]
Epoch 140
0.04543516
(0.175, 0.18333333333333335)
[1 3 3 3 1 3 3 6] [1 3 6 1 6 4 6 2]
Epoch 160
0.028924566
(0.13999999999999999, 0.16666666666666669)
[1 3 3 3 6 1 3 3] [1 6 6 1 2 6 4 3]
Epoch 180
0.01933351
(0.13999999999999999, 0.16666666666666669)

Max UAR:0.175 at epoch 60
Max UF1:0.18333333333333335 at epoch 60
Test 2


[2] [4]
Epoch 0
1.9502271
(0.0, 0.0)
[2] [6]
Epoch 20
1.0738477
(0.0, 0.0)
[2] [3]
Epoch 40
0.6262135
(0.0, 0.0)
[2] [3]
Epoch 60
0.366166
(0.0, 0.0)
[2] [3]
Epoch 80
0.21263641
(0.0, 0.0)
[2] [3]
Epoch 100
0.123899244
(0.0, 0.0)
[2] [1]
Epoch 120
0.074633375
(0.0, 0.0)
[2] [1]
Epoch 140
0.046007555
(0.0, 0.0)
[2] [1]
Epoch 160
0.029392565
(0.0, 0.0)
[2] [1]
Epoch 180
0.019773964
(0.0, 0.0)

Max UAR:0.0 at epoch 0
Max UF1:0.0 at epoch 0
Test 3


[1 1 1] [6 6 6]
Epoch 0
1.9529438
(0.0, 0.0)
[1 1 1] [3 6 3]
Epoch 20
1.0618755
(0.0, 0.0)
[1 1 1] [3 3 6]
Epoch 40
0.6113782
(0.0, 0.0)
[1 1 1] [6 3 3]
Epoch 60
0.35607794
(0.0, 0.0)
[1 1 1] [3 6 3]
Epoch 80
0.20610483
(0.0, 0.0)
[1 1 1] [6 3 3]
Epoch 100
0.11986481
(0.0, 0.0)
[1 1 1] [3 6 3]
Epoch 120
0.07213125
(0.0, 0.0)
[1 1 1] [3 3 6]
Epoch 140
0.04446114
(0.0, 0.0)
[1 1 1] [3 6 3]
Epoch 160
0.028337277
(0.0, 0.0)
[1 1 1] [6 3 3]
Epoch 180
0.018989395
(0.0, 0.0)

Max UAR:0.0 at epoch 0
Max UF1:0.0 at epoch 0
Test 4


[6 0 0] [4 4 3]
Epoch 0
1.94798
(0.0, 0.0)
[0 0 6] [6 3 4]
Epoch 20
1.0738841
(0.0, 0.0)
[0 0 6] [1 6 4]
Epoch 40
0.61322254
(0.0, 0.0)
[0 0 6] [1 6 5]
Epoch 60
0.3556843
(0.0, 0.0)
[6 0 0] [5 1 6]
Epoch 80
0.20521785
(0.0, 0.0)
[6 0 0] [5 1 6]
Epoch 100
0.119546495
(0.0, 0.0)
[0 0 6] [6 1 1]
Epoch 120
0.07231504
(0.0, 0.0)
[0 0 6] [1 6 1]
Epoch 140
0.044794757
(0.0, 0.0)
[0 0 6] [1 6 1]
Epoch 160
0.028676411
(0.0, 0.0)
[0 6 0] [6 1 1]
Epoch 180
0.01929831
(0.0, 0.0)

Max UAR:0.0 at epoch 0
Max UF1:0.0 at epoch 0
Test 5


[1 1 1] [4 4 4]
Epoch 0
1.9526566
(0.0, 0.0)
[1 1 1] [1 4 5]
Epoch 20
1.0672538
(0.1111111111111111, 0.16666666666666666)
[1 1 1] [4 5 1]
Epoch 40
0.6112134
(0.1111111111111111, 0.16666666666666666)
[1 1 1] [1 4 3]
Epoch 60
0.35527408
(0.1111111111111111, 0.16666666666666666)
[1 1 1] [4 3 1]
Epoch 80
0.20705548
(0.1111111111111111, 0.16666666666666666)
[1 1 1] [4 6 1]
Epoch 100
0.1217657
(0.1111111111111111, 0.16666666666666666)
[1 1 1] [1 4 6]
Epoch 120
0.0740207
(0.1111111111111111, 0.16666666666666666)
[1 1 1] [1 4 6]
Epoch 140
0.04583381
(0.1111111111111111, 0.16666666666666666)
[1 1 1] [1 6 4]
Epoch 160
0.029178448
(0.1111111111111111, 0.16666666666666666)
[1 1 1] [4 1 6]
Epoch 180
0.019506583
(0.1111111111111111, 0.16666666666666666)

Max UAR:0.1111111111111111 at epoch 20
Max UF1:0.16666666666666666 at epoch 20
Test 6


[1 6 3 0 0 3 1 1 6 6 6] [4 4 4 4 4 3 4 1 1 4 1]
Epoch 0
1.9526037
(0.16666666666666666, 0.2)
[6 3 3 1 6 1 6 0 0 1 6] [1 3 4 1 3 4 2 4 1 4 6]
Epoch 20
1.0568353
(0.18055555555555555, 0.20555555555555557)
[6 3 0 6 6 1 0 1 6 1 3] [2 3 1 3 1 2 1 1 6 2 5]
Epoch 40
0.59860075
(0.18055555555555555, 0.19761904761904767)
[6 1 6 6 0 1 3 1 3 0 6] [4 1 3 6 1 2 3 2 4 1 1]
Epoch 60
0.3449528
(0.18055555555555555, 0.19761904761904767)
[6 1 6 1 3 0 0 3 6 6 1] [3 6 4 2 4 1 1 3 1 6 2]
Epoch 80
0.19764772
(0.125, 0.13888888888888887)
[1 0 6 6 3 1 6 6 3 1 0] [3 1 1 4 4 1 3 6 3 2 1]
Epoch 100
0.11266196
(0.18055555555555555, 0.18095238095238098)
[1 0 0 3 3 6 6 6 6 1 1] [1 1 1 4 6 6 1 3 4 3 1]
Epoch 120
0.0664086
(0.18333333333333332, 0.16666666666666666)
[6 1 1 0 0 6 1 6 3 6 3] [4 1 1 1 1 6 3 1 4 3 6]
Epoch 140
0.04068964
(0.18333333333333332, 0.16666666666666666)
[0 6 6 1 1 0 3 6 3 1 6] [1 1 3 3 1 1 6 1 4 1 6]
Epoch 160
0.02621941
(0.18333333333333332, 0.15555555555555553)
[1 3 6 0 6 1 0 1 6 3 6] [1 4 1 1

[2] [4]
Epoch 0
1.951152
(0.0, 0.0)
[2] [4]
Epoch 20
1.0710847
(0.0, 0.0)
[2] [4]
Epoch 40
0.61553913
(0.0, 0.0)
[2] [1]
Epoch 60
0.3581796
(0.0, 0.0)
[2] [1]
Epoch 80
0.20666479
(0.0, 0.0)
[2] [4]
Epoch 100
0.11997083
(0.0, 0.0)
[2] [4]
Epoch 120
0.072179995
(0.0, 0.0)
[2] [4]
Epoch 140
0.04443105
(0.0, 0.0)
[2] [4]
Epoch 160
0.028334422
(0.0, 0.0)
[2] [4]
Epoch 180
0.019046264
(0.0, 0.0)

Max UAR:0.0 at epoch 0
Max UF1:0.0 at epoch 0
Test 8


[1 0] [4 4]
Epoch 0
1.9499989
(0.0, 0.0)
[0 1] [4 4]
Epoch 20
1.0765498
(0.0, 0.0)
[1 0] [4 4]
Epoch 40
0.6167238
(0.0, 0.0)
[1 0] [4 4]
Epoch 60
0.3572944
(0.0, 0.0)
[0 1] [0 4]
Epoch 80
0.20640826
(0.3333333333333333, 0.3333333333333333)
[0 1] [0 4]
Epoch 100
0.120322734
(0.3333333333333333, 0.3333333333333333)
[0 1] [0 1]
Epoch 120
0.07231579
(1.0, 1.0)
[1 0] [1 0]
Epoch 140
0.044197444
(1.0, 1.0)
[1 0] [1 0]
Epoch 160
0.027957352
(1.0, 1.0)
[1 0] [1 3]
Epoch 180
0.01859978
(0.3333333333333333, 0.3333333333333333)

Max UAR:1.0 at epoch 120
Max UF1:1.0 at epoch 120
Test 9


[0 0 1 3 6 0] [6 4 4 4 4 4]
Epoch 0
1.9487935
(0.0, 0.0)
[0 6 1 3 0 0] [4 6 4 4 4 4]
Epoch 20
1.0387408
(0.2, 0.2)
[0 1 6 0 3 0] [4 4 6 4 4 4]
Epoch 40
0.58600473
(0.2, 0.2)
[3 1 0 0 0 6] [4 4 4 4 4 6]
Epoch 60
0.34307662
(0.2, 0.2)
[6 0 0 0 1 3] [6 4 4 4 4 4]
Epoch 80
0.19987181
(0.2, 0.2)
[0 1 0 0 6 3] [4 4 4 1 6 4]
Epoch 100
0.117435925
(0.2, 0.2)
[0 0 0 3 1 6] [4 4 1 4 4 6]
Epoch 120
0.070990525
(0.2, 0.2)
[0 3 0 6 0 1] [4 4 4 6 1 4]
Epoch 140
0.043790832
(0.2, 0.2)
[0 0 3 0 1 6] [1 1 4 4 4 6]
Epoch 160
0.027930448
(0.2, 0.2)
[6 3 0 0 1 0] [6 4 1 1 4 4]
Epoch 180
0.018663794
(0.2, 0.2)

Max UAR:0.2 at epoch 20
Max UF1:0.2 at epoch 20
Test 10


[1 6 2 6 2 3] [4 6 4 6 4 6]
Epoch 0
1.9527999
(0.2, 0.16)
[2 3 6 1 6 2] [5 6 6 5 6 5]
Epoch 20
1.0524142
(0.2, 0.16)
[1 6 2 3 6 2] [5 6 5 6 1 4]
Epoch 40
0.58774245
(0.08333333333333333, 0.08333333333333333)
[3 2 1 2 6 6] [6 4 1 5 6 1]
Epoch 60
0.335456
(0.25, 0.19444444444444442)
[3 6 1 6 2 2] [6 1 1 6 4 5]
Epoch 80
0.19760819
(0.25, 0.19444444444444442)
[1 6 6 2 2 3] [1 1 6 4 5 6]
Epoch 100
0.11864867
(0.25, 0.19444444444444442)
[3 1 6 2 6 2] [6 1 6 4 5 5]
Epoch 120
0.07273397
(0.25, 0.25)
[3 1 2 2 6 6] [6 1 4 5 6 5]
Epoch 140
0.045206346
(0.25, 0.25)
[2 6 2 6 3 1] [4 6 5 5 6 1]
Epoch 160
0.028871976
(0.25, 0.25)
[2 6 1 2 6 3] [5 5 1 4 6 6]
Epoch 180
0.019356297
(0.25, 0.25)

Max UAR:0.25 at epoch 60
Max UF1:0.25 at epoch 120
Test 11


[5 3] [4 4]
Epoch 0
1.9552867
(0.0, 0.0)
[5 3] [2 4]
Epoch 20
1.0698142
(0.0, 0.0)
[5 3] [1 6]
Epoch 40
0.6142185
(0.0, 0.0)
[5 3] [1 6]
Epoch 60
0.35745344
(0.0, 0.0)
[5 3] [1 6]
Epoch 80
0.2087403
(0.0, 0.0)
[3 5] [6 1]
Epoch 100
0.12316052
(0.0, 0.0)
[5 3] [1 4]
Epoch 120
0.075186715
(0.0, 0.0)
[3 5] [4 1]
Epoch 140
0.04695405
(0.0, 0.0)
[3 5] [4 1]
Epoch 160
0.03019485
(0.0, 0.0)
[5 3] [1 4]
Epoch 180
0.020285424
(0.0, 0.0)

Max UAR:0.0 at epoch 0
Max UF1:0.0 at epoch 0
Test 12


[3] [1]
Epoch 0
1.95234
(0.0, 0.0)
[3] [4]
Epoch 20
1.0694159
(0.0, 0.0)
[3] [1]
Epoch 40
0.6154783
(0.0, 0.0)
[3] [1]
Epoch 60
0.35910603
(0.0, 0.0)
[3] [1]
Epoch 80
0.20969805
(0.0, 0.0)
[3] [1]
Epoch 100
0.123278186
(0.0, 0.0)
[3] [1]
Epoch 120
0.074702956
(0.0, 0.0)
[3] [1]
Epoch 140
0.04619693
(0.0, 0.0)
[3] [1]
Epoch 160
0.029513214
(0.0, 0.0)
[3] [1]
Epoch 180
0.019821744
(0.0, 0.0)

Max UAR:0.0 at epoch 0
Max UF1:0.0 at epoch 0
Test 13


[3 4 4 4 4 4 1 4 1 4 4 4 3 4 4 4 6 4 6 4 4 1] [1 1 1 1 3 4 1 1 1 1 1 1 3 1 1 1 1 5 1 1 1 1]
Epoch 0
1.9491981
(0.31333333333333335, 0.18214285714285713)
[4 4 4 3 4 4 4 4 4 1 1 4 6 4 4 4 1 4 4 6 3 4] [6 1 4 1 5 1 1 3 4 3 3 6 1 6 2 3 1 1 4 1 3 4]
Epoch 20
1.0297247
(0.18333333333333332, 0.14809751651856917)
[1 4 3 4 4 4 4 4 4 1 3 1 4 4 6 6 4 4 4 4 4 4] [1 4 3 4 4 1 1 4 4 3 3 3 5 4 1 1 4 1 4 1 3 3]
Epoch 40
0.5826623
(0.37333333333333335, 0.27913043478260874)
[4 6 4 4 4 6 4 4 4 4 4 4 1 4 3 4 4 1 4 1 4 3] [4 1 4 4 4 1 1 1 5 4 3 4 3 1 3 1 3 1 4 3 1 3]
Epoch 60
0.33125964
(0.36, 0.26363636363636367)
[3 4 1 4 4 6 4 4 4 4 3 4 4 1 1 4 4 4 4 6 4 4] [3 1 3 1 4 1 4 1 0 1 3 4 5 1 3 3 4 4 1 1 4 3]
Epoch 80
0.18669066
(0.2888888888888889, 0.20887445887445888)
[4 1 4 1 4 4 4 4 3 4 4 3 4 4 1 4 4 4 4 6 6 4] [0 1 1 3 1 4 3 4 3 3 4 3 4 1 3 4 1 1 4 1 1 4]
Epoch 100
0.107237555
(0.36, 0.26363636363636367)
[4 4 4 4 6 6 4 4 4 1 4 1 4 4 4 3 4 3 1 4 4 4] [4 1 3 1 1 1 1 4 4 3 1 1 4 1 4 3 0 3 3 4 4 4]
Epoch 120
0

[1] [4]
Epoch 0
1.9524919
(0.0, 0.0)
[1] [2]
Epoch 20
1.0680871
(0.0, 0.0)
[1] [4]
Epoch 40
0.61340624
(0.0, 0.0)
[1] [4]
Epoch 60
0.3576709
(0.0, 0.0)
[1] [1]
Epoch 80
0.20825817
(1.0, 1.0)
[1] [1]
Epoch 100
0.12199474
(1.0, 1.0)
[1] [1]
Epoch 120
0.07424526
(1.0, 1.0)
[1] [1]
Epoch 140
0.04621686
(1.0, 1.0)
[1] [1]
Epoch 160
0.029592171
(1.0, 1.0)
[1] [1]
Epoch 180
0.01980648
(1.0, 1.0)

Max UAR:1.0 at epoch 80
Max UF1:1.0 at epoch 80
Test 15


[6] [4]
Epoch 0
1.952697
(0.0, 0.0)
[6] [5]
Epoch 20
1.0694617
(0.0, 0.0)
[6] [6]
Epoch 40
0.61584485
(1.0, 1.0)
[6] [6]
Epoch 60
0.35880733
(1.0, 1.0)
[6] [6]
Epoch 80
0.2082901
(1.0, 1.0)
[6] [6]
Epoch 100
0.12148774
(1.0, 1.0)
[6] [6]
Epoch 120
0.07318891
(1.0, 1.0)
[6] [6]
Epoch 140
0.045122676
(1.0, 1.0)
[6] [6]
Epoch 160
0.028784512
(1.0, 1.0)
[6] [6]
Epoch 180
0.019300805
(1.0, 1.0)

Max UAR:1.0 at epoch 40
Max UF1:1.0 at epoch 40
Test 16


[6 6 3 6 4 4 3 4 4 4 3 4 6 4] [4 4 1 4 4 4 4 4 1 4 4 4 1 4]
Epoch 0
1.9522107
(0.21428571428571427, 0.16666666666666663)
[4 4 6 4 4 4 3 4 6 6 4 3 6 3] [3 4 5 4 4 4 1 1 5 5 1 5 6 3]
Epoch 20
1.0481108
(0.23095238095238094, 0.3054545454545455)
[4 6 4 4 6 4 6 4 3 3 4 3 6 4] [1 5 4 4 5 3 6 4 6 3 4 3 6 3]
Epoch 40
0.5889043
(0.3476190476190476, 0.37402597402597404)
[4 4 4 3 3 6 3 6 4 4 6 4 4 6] [3 4 4 3 6 6 3 3 4 4 6 3 4 5]
Epoch 60
0.33321902
(0.47023809523809523, 0.47619047619047616)
[4 3 3 4 4 4 4 6 4 3 6 4 6 6] [3 3 3 4 4 4 3 5 4 4 6 4 4 6]
Epoch 80
0.18851419
(0.47023809523809523, 0.48809523809523814)
[6 6 4 6 4 4 6 4 3 4 3 4 3 4] [6 5 4 4 4 3 6 3 3 4 3 4 4 4]
Epoch 100
0.10856607
(0.47023809523809523, 0.48809523809523814)
[6 3 4 4 4 4 6 4 6 4 3 4 3 6] [5 4 4 4 4 1 3 3 6 4 3 4 3 6]
Epoch 120
0.064907655
(0.3761904761904762, 0.4014652014652015)
[6 3 4 6 3 4 6 4 4 4 3 4 4 6] [6 3 4 5 3 4 3 4 3 4 4 1 4 6]
Epoch 140
0.039931588
(0.3761904761904762, 0.4014652014652015)
[3 4 6 3 4 4 4 6 4 6 

[4 4 4 4 3 4 2 4 4] [3 4 4 4 4 4 4 4 6]
Epoch 0
1.9488963
(0.17857142857142858, 0.17857142857142858)
[2 3 4 4 4 4 4 4 4] [4 5 0 5 4 2 4 0 5]
Epoch 20
1.0446895
(0.05714285714285714, 0.08)
[2 4 4 3 4 4 4 4 4] [6 5 1 3 0 0 4 0 5]
Epoch 40
0.57801557
(0.16326530612244897, 0.17857142857142858)
[4 4 4 4 4 3 4 2 4] [0 6 6 5 3 3 6 6 1]
Epoch 60
0.32354787
(0.14285714285714285, 0.09523809523809523)
[4 4 4 3 4 4 4 2 4] [5 0 6 1 6 1 3 6 6]
Epoch 80
0.17853107
(0.0, 0.0)
[2 4 4 4 4 4 3 4 4] [6 3 6 1 6 5 1 0 6]
Epoch 100
0.09917655
(0.0, 0.0)
[4 4 4 4 4 4 4 3 2] [3 6 0 1 3 5 6 4 6]
Epoch 120
0.05756071
(0.0, 0.0)
[4 4 4 4 3 4 2 4 4] [6 3 1 1 4 6 6 0 5]
Epoch 140
0.035052788
(0.0, 0.0)
[4 4 4 4 4 3 2 4 4] [0 6 3 1 6 4 6 1 5]
Epoch 160
0.022626823
(0.0, 0.0)
[4 2 4 4 4 4 3 4 4] [6 6 1 5 0 3 4 6 1]
Epoch 180
0.015544688
(0.0, 0.0)

Max UAR:0.17857142857142858 at epoch 0
Max UF1:0.17857142857142858 at epoch 0
Test 18


[1 1 1 1 1 1 1 1 1 1 1 1 6 1 1 1 5 1 1 6 4 1 1] [4 6 4 4 4 6 1 4 6 4 6 6 3 4 4 6 4 4 4 4 4 4 4]
Epoch 0
1.9560632
(0.21052631578947367, 0.045)
[1 1 1 1 1 1 1 1 1 1 1 1 1 6 1 6 5 1 1 1 1 1 4] [1 1 1 1 6 1 4 5 1 1 1 4 4 4 1 1 6 4 1 1 1 4 6]
Epoch 20
1.0819501
(0.15789473684210525, 0.18749999999999997)
[1 1 1 1 1 1 1 1 1 1 1 1 1 4 1 1 1 1 1 5 6 1 6] [1 6 1 1 3 1 4 1 4 1 1 4 1 6 1 1 4 4 1 6 4 1 6]
Epoch 40
0.6214955
(0.2263157894736842, 0.221505376344086)
[1 1 1 1 1 1 1 1 1 4 1 1 1 1 5 1 1 1 6 1 1 1 6] [1 1 4 1 1 4 1 1 1 6 1 4 6 1 6 3 3 4 6 1 1 1 4]
Epoch 60
0.3537912
(0.2263157894736842, 0.221505376344086)
[5 1 1 1 1 4 1 1 1 1 1 1 1 1 1 1 1 1 6 6 1 1 1] [6 1 1 1 1 6 4 6 4 1 4 6 1 1 4 1 6 4 4 6 1 3 1]
Epoch 80
0.19938415
(0.20526315789473681, 0.18793103448275864)
[6 1 1 1 1 1 1 1 5 1 1 1 1 1 1 1 4 6 1 1 1 1 1] [4 4 1 1 4 4 6 4 6 1 1 1 1 1 1 6 6 6 6 6 1 1 4]
Epoch 100
0.11514428
(0.256578947368421, 0.22796934865900384)
[1 1 1 6 1 1 1 1 1 1 1 6 1 1 1 1 1 1 4 1 5 1 1] [1 1 6 4 1 4 1 4 4 1 1 6

[2 5 5 4 4] [3 4 6 4 4]
Epoch 0
1.9549456
(0.2, 0.16)
[2 5 4 4 5] [3 5 5 4 4]
Epoch 20
1.0745541
(0.25, 0.25)
[4 4 5 2 5] [6 4 6 3 4]
Epoch 40
0.61730486
(0.1, 0.1)
[5 5 4 2 4] [6 4 6 3 4]
Epoch 60
0.35600075
(0.1, 0.1)
[5 5 2 4 4] [4 6 3 6 4]
Epoch 80
0.20668985
(0.1, 0.1)
[4 5 5 4 2] [4 6 3 6 3]
Epoch 100
0.12194554
(0.1, 0.13333333333333333)
[4 4 5 5 2] [4 4 3 6 3]
Epoch 120
0.073918894
(0.2, 0.2)
[4 2 5 5 4] [4 3 3 6 4]
Epoch 140
0.04570185
(0.2, 0.2)
[4 5 4 5 2] [4 6 4 3 3]
Epoch 160
0.029247006
(0.2, 0.2)
[2 5 5 4 4] [3 3 6 4 4]
Epoch 180
0.019654714
(0.2, 0.2)

Max UAR:0.25 at epoch 20
Max UF1:0.25 at epoch 20
Test 20


[5 6 6 6] [1 4 1 1]
Epoch 0
1.9523323
(0.0, 0.0)
[6 6 6 5] [1 1 6 1]
Epoch 20
1.0899079
(0.1111111111111111, 0.16666666666666666)
[6 5 6 6] [1 1 1 1]
Epoch 40
0.62775815
(0.0, 0.0)
[6 6 6 5] [1 1 1 1]
Epoch 60
0.36419553
(0.0, 0.0)
[6 5 6 6] [1 1 1 1]
Epoch 80
0.20978329
(0.0, 0.0)
[6 6 5 6] [1 1 1 1]
Epoch 100
0.121211745
(0.0, 0.0)
[6 6 6 5] [1 1 1 1]
Epoch 120
0.07245804
(0.0, 0.0)
[6 5 6 6] [1 1 1 1]
Epoch 140
0.044393606
(0.0, 0.0)
[6 6 6 5] [1 1 1 1]
Epoch 160
0.028249055
(0.0, 0.0)
[6 6 5 6] [1 1 1 1]
Epoch 180
0.018960467
(0.0, 0.0)

Max UAR:0.1111111111111111 at epoch 20
Max UF1:0.16666666666666666 at epoch 20
Test 21


[3 6] [4 4]
Epoch 0
1.9527832
(0.0, 0.0)
[6 3] [6 1]
Epoch 20
1.068577
(0.3333333333333333, 0.3333333333333333)
[3 6] [1 6]
Epoch 40
0.61429924
(0.3333333333333333, 0.3333333333333333)
[3 6] [1 6]
Epoch 60
0.35755584
(0.3333333333333333, 0.3333333333333333)
[6 3] [6 1]
Epoch 80
0.20715423
(0.3333333333333333, 0.3333333333333333)
[6 3] [6 1]
Epoch 100
0.120500386
(0.3333333333333333, 0.3333333333333333)
[3 6] [1 6]
Epoch 120
0.07248874
(0.3333333333333333, 0.3333333333333333)
[6 3] [6 1]
Epoch 140
0.044611875
(0.3333333333333333, 0.3333333333333333)
[3 6] [1 6]
Epoch 160
0.028425053
(0.3333333333333333, 0.3333333333333333)
[6 3] [6 1]
Epoch 180
0.019070512
(0.3333333333333333, 0.3333333333333333)

Max UAR:0.3333333333333333 at epoch 20
Max UF1:0.3333333333333333 at epoch 20
Test 22


[4 4 4 6 1 4 4] [4 4 4 4 4 4 4]
Epoch 0
1.9518684
(0.3333333333333333, 0.27777777777777773)
[6 4 4 4 4 1 4] [6 4 4 3 3 3 3]
Epoch 20
1.0577703
(0.35, 0.3928571428571429)
[4 6 4 4 4 1 4] [4 6 3 2 3 3 3]
Epoch 40
0.5967759
(0.24, 0.2666666666666667)
[4 4 4 4 4 1 6] [4 3 4 3 3 3 6]
Epoch 60
0.33917534
(0.35, 0.3928571428571429)
[6 4 4 4 1 4 4] [6 4 4 3 3 3 3]
Epoch 80
0.19133012
(0.35, 0.3928571428571429)
[6 4 1 4 4 4 4] [6 3 3 3 4 3 4]
Epoch 100
0.10974782
(0.35, 0.3928571428571429)
[1 4 4 4 4 4 6] [4 3 3 4 3 4 6]
Epoch 120
0.06563307
(0.35, 0.375)
[4 4 4 6 4 4 1] [3 3 4 6 4 3 4]
Epoch 140
0.040437855
(0.35, 0.375)
[4 4 4 4 4 6 1] [3 4 3 4 3 6 4]
Epoch 160
0.025886633
(0.35, 0.375)
[6 4 4 1 4 4 4] [6 4 3 4 3 4 3]
Epoch 180
0.017461427
(0.35, 0.375)

Max UAR:0.35 at epoch 20
Max UF1:0.3928571428571429 at epoch 20
Test 23


[6 1 1 1 1 6 1] [6 4 3 6 1 4 6]
Epoch 0
1.9544573
(0.175, 0.18333333333333335)
[6 1 1 1 6 1 1] [6 6 6 1 1 3 6]
Epoch 20
1.0699935
(0.2333333333333333, 0.20634920634920637)
[1 6 1 6 1 1 1] [3 6 3 6 3 6 1]
Epoch 40
0.61902976
(0.39999999999999997, 0.37777777777777777)
[1 1 6 1 6 1 1] [6 3 6 1 6 3 3]
Epoch 60
0.3621989
(0.39999999999999997, 0.37777777777777777)
[6 6 1 1 1 1 1] [6 6 6 1 6 3 3]
Epoch 80
0.21005644
(0.39999999999999997, 0.3333333333333333)
[6 1 1 1 1 1 6] [6 3 3 1 6 6 6]
Epoch 100
0.12201829
(0.39999999999999997, 0.3333333333333333)
[1 1 1 6 6 1 1] [1 6 3 6 6 3 6]
Epoch 120
0.072844215
(0.39999999999999997, 0.3333333333333333)
[1 6 1 1 1 1 6] [3 6 1 6 5 3 6]
Epoch 140
0.04470795
(0.3, 0.2833333333333333)
[6 1 1 6 1 1 1] [6 3 3 6 5 1 6]
Epoch 160
0.028537452
(0.3, 0.2833333333333333)
[6 1 6 1 1 1 1] [6 5 6 1 6 3 3]
Epoch 180
0.019212343
(0.3, 0.2833333333333333)

Max UAR:0.39999999999999997 at epoch 40
Max UF1:0.37777777777777777 at epoch 40
Test 24


[1] [4]
Epoch 0
1.952554
(0.0, 0.0)
[1] [3]
Epoch 20
1.068679
(0.0, 0.0)
[1] [3]
Epoch 40
0.61323553
(0.0, 0.0)
[1] [3]
Epoch 60
0.35602495
(0.0, 0.0)
[1] [3]
Epoch 80
0.20615433
(0.0, 0.0)
[1] [3]
Epoch 100
0.12035683
(0.0, 0.0)
[1] [3]
Epoch 120
0.07276437
(0.0, 0.0)
[1] [3]
Epoch 140
0.04499198
(0.0, 0.0)
[1] [3]
Epoch 160
0.028793527
(0.0, 0.0)
[1] [3]
Epoch 180
0.019363843
(0.0, 0.0)

Max UAR:0.0 at epoch 0
Max UF1:0.0 at epoch 0
Test 25


[6 3 3] [4 4 4]
Epoch 0
1.9531409
(0.0, 0.0)
[3 6 3] [5 4 4]
Epoch 20
1.0645083
(0.0, 0.0)
[3 3 6] [6 4 4]
Epoch 40
0.6062503
(0.0, 0.0)
[3 3 6] [6 4 2]
Epoch 60
0.353797
(0.0, 0.0)
[3 6 3] [4 2 6]
Epoch 80
0.20761102
(0.0, 0.0)
[6 3 3] [2 4 4]
Epoch 100
0.122227974
(0.0, 0.0)
[6 3 3] [2 4 4]
Epoch 120
0.073947996
(0.0, 0.0)
[3 3 6] [4 4 2]
Epoch 140
0.045738053
(0.0, 0.0)
[3 6 3] [4 2 4]
Epoch 160
0.02927594
(0.0, 0.0)
[3 6 3] [4 2 4]
Epoch 180
0.0196662
(0.0, 0.0)

Max UAR:0.0 at epoch 0
Max UF1:0.0 at epoch 0
Test 26


[1 1 6 1 5] [4 4 4 4 4]
Epoch 0
1.9547683
(0.0, 0.0)
[6 1 1 1 5] [6 3 1 1 3]
Epoch 20
1.063971
(0.41666666666666663, 0.45)
[1 6 1 1 5] [1 6 1 3 6]
Epoch 40
0.60154
(0.41666666666666663, 0.3666666666666667)
[1 1 5 6 1] [1 3 6 6 1]
Epoch 60
0.3415082
(0.41666666666666663, 0.3666666666666667)
[1 5 1 6 1] [1 6 1 6 3]
Epoch 80
0.19721183
(0.41666666666666663, 0.3666666666666667)
[5 1 6 1 1] [6 1 6 1 3]
Epoch 100
0.11726223
(0.41666666666666663, 0.3666666666666667)
[1 1 6 5 1] [1 3 6 6 1]
Epoch 120
0.07267953
(0.41666666666666663, 0.3666666666666667)
[1 5 1 6 1] [1 6 1 6 3]
Epoch 140
0.045921557
(0.41666666666666663, 0.3666666666666667)
[6 5 1 1 1] [6 6 1 3 1]
Epoch 160
0.029710772
(0.41666666666666663, 0.3666666666666667)
[1 5 1 1 6] [1 6 1 3 6]
Epoch 180
0.020097703
(0.41666666666666663, 0.3666666666666667)

Max UAR:0.41666666666666663 at epoch 20
Max UF1:0.45 at epoch 20
Test 27


[1 1 1 1 1 1 1 4 1] [6 4 4 3 4 4 4 6 4]
Epoch 0
1.9520949
(0.0, 0.0)
[1 1 4 1 1 1 1 1 1] [1 4 4 1 1 6 1 2 4]
Epoch 20
1.0712383
(0.375, 0.29166666666666663)
[1 1 1 4 1 1 1 1 1] [1 4 1 4 1 2 4 1 1]
Epoch 40
0.616287
(0.5416666666666666, 0.4230769230769231)
[1 1 1 1 1 1 1 1 4] [1 2 4 1 1 1 1 1 4]
Epoch 60
0.3572393
(0.5833333333333334, 0.5079365079365079)
[1 1 1 1 1 4 1 1 1] [1 1 1 1 1 4 1 4 1]
Epoch 80
0.20568167
(0.9375, 0.8)
[1 1 1 1 1 4 1 1 1] [1 1 1 1 1 4 1 1 4]
Epoch 100
0.119061865
(0.9375, 0.8)
[1 1 1 1 1 1 4 1 1] [1 1 1 1 1 1 4 1 4]
Epoch 120
0.07110479
(0.9375, 0.8)
[1 4 1 1 1 1 1 1 1] [1 4 1 1 1 1 1 1 4]
Epoch 140
0.043527223
(0.9375, 0.8)
[1 1 1 1 4 1 1 1 1] [1 1 1 1 4 1 1 1 4]
Epoch 160
0.027694987
(0.9375, 0.8)
[1 1 1 1 1 1 1 1 4] [1 1 1 1 1 1 4 1 4]
Epoch 180
0.018603949
(0.9375, 0.8)

Max UAR:0.9375 at epoch 80
Max UF1:0.8 at epoch 80
Test 28


[6 4 3] [1 4 4]
Epoch 0
1.9524579
(0.25, 0.16666666666666666)
[4 3 6] [3 3 3]
Epoch 20
1.0662264
(0.3333333333333333, 0.16666666666666666)
[3 4 6] [3 4 3]
Epoch 40
0.6114225
(0.6666666666666666, 0.5555555555555555)
[4 3 6] [4 3 3]
Epoch 60
0.3568148
(0.6666666666666666, 0.5555555555555555)
[3 4 6] [3 4 3]
Epoch 80
0.20782924
(0.6666666666666666, 0.5555555555555555)
[3 4 6] [3 4 3]
Epoch 100
0.121392764
(0.6666666666666666, 0.5555555555555555)
[6 3 4] [3 3 4]
Epoch 120
0.07314998
(0.6666666666666666, 0.5555555555555555)
[3 4 6] [3 4 3]
Epoch 140
0.044902306
(0.6666666666666666, 0.5555555555555555)
[6 4 3] [3 4 3]
Epoch 160
0.028426945
(0.6666666666666666, 0.5555555555555555)
[4 6 3] [4 3 3]
Epoch 180
0.0189904
(0.6666666666666666, 0.5555555555555555)

Max UAR:0.6666666666666666 at epoch 40
Max UF1:0.5555555555555555 at epoch 40
Test 29


[1 3 1] [6 6 4]
Epoch 0
1.9528122
(0.0, 0.0)
[1 1 3] [6 3 1]
Epoch 20
1.0670767
(0.0, 0.0)
[3 1 1] [1 6 3]
Epoch 40
0.6122259
(0.0, 0.0)
[3 1 1] [1 6 5]
Epoch 60
0.3566117
(0.0, 0.0)
[1 1 3] [6 5 1]
Epoch 80
0.20914611
(0.0, 0.0)
[3 1 1] [1 6 5]
Epoch 100
0.123639315
(0.0, 0.0)
[3 1 1] [1 5 6]
Epoch 120
0.075583346
(0.0, 0.0)
[1 1 3] [5 6 1]
Epoch 140
0.047142927
(0.0, 0.0)
[3 1 1] [1 6 5]
Epoch 160
0.03020243
(0.0, 0.0)
[1 1 3] [6 5 1]
Epoch 180
0.02019284
(0.0, 0.0)

Max UAR:0.0 at epoch 0
Max UF1:0.0 at epoch 0
Test 30


[4 3 4 6 6 4 4 4 6] [3 4 4 4 1 1 4 1 6]
Epoch 0
1.9531258
(0.18333333333333335, 0.2361111111111111)
[6 4 4 4 6 6 4 4 3] [1 1 3 0 5 5 1 3 5]
Epoch 20
1.0701659
(0.0, 0.0)
[4 4 6 6 4 4 3 6 4] [4 1 6 6 3 4 6 1 3]
Epoch 40
0.61003006
(0.26666666666666666, 0.30952380952380953)
[4 4 4 4 4 3 6 6 6] [3 4 1 4 3 6 1 6 6]
Epoch 60
0.352189
(0.26666666666666666, 0.30952380952380953)
[6 4 6 4 4 4 3 4 6] [6 4 6 1 3 4 6 4 1]
Epoch 80
0.2026624
(0.31666666666666665, 0.35416666666666663)
[4 4 4 4 6 4 6 6 3] [4 3 6 1 6 4 6 1 6]
Epoch 100
0.11742866
(0.26666666666666666, 0.28571428571428575)
[4 6 6 4 6 4 4 4 3] [3 6 6 4 1 6 1 4 6]
Epoch 120
0.07010302
(0.26666666666666666, 0.28571428571428575)
[4 4 6 4 4 3 4 6 6] [1 3 1 4 6 6 4 6 6]
Epoch 140
0.042779405
(0.26666666666666666, 0.28571428571428575)
[6 4 6 3 4 6 4 4 4] [6 3 6 6 1 1 6 4 4]
Epoch 160
0.027164156
(0.26666666666666666, 0.28571428571428575)
[3 6 4 6 4 4 4 4 6] [6 1 4 6 1 6 4 3 6]
Epoch 180
0.018220704
(0.26666666666666666, 0.28571428571428575)



[1 6 1 1 1] [4 4 4 1 4]
Epoch 0
1.9530382
(0.08333333333333333, 0.13333333333333333)
[1 1 6 1 1] [4 1 5 2 1]
Epoch 20
1.0655272
(0.1, 0.13333333333333333)
[1 1 6 1 1] [4 4 5 1 4]
Epoch 40
0.6097335
(0.0625, 0.1)
[1 1 1 1 6] [1 1 4 1 5]
Epoch 60
0.35452121
(0.1875, 0.21428571428571427)
[6 1 1 1 1] [5 4 1 1 1]
Epoch 80
0.2064098
(0.1875, 0.21428571428571427)
[1 1 1 6 1] [1 1 4 5 1]
Epoch 100
0.11998854
(0.1875, 0.21428571428571427)
[1 6 1 1 1] [1 5 4 1 1]
Epoch 120
0.0718224
(0.1875, 0.21428571428571427)
[1 1 6 1 1] [1 1 5 4 1]
Epoch 140
0.04408507
(0.1875, 0.21428571428571427)
[1 1 1 6 1] [1 4 1 5 1]
Epoch 160
0.028116504
(0.1875, 0.21428571428571427)
[1 1 1 6 1] [1 4 1 5 1]
Epoch 180
0.01890749
(0.1875, 0.21428571428571427)

Max UAR:0.1875 at epoch 60
Max UF1:0.21428571428571427 at epoch 60
Test 32


[1 1] [4 4]
Epoch 0
1.9522469
(0.0, 0.0)
[1 1] [4 1]
Epoch 20
1.0710521
(0.25, 0.3333333333333333)
[1 1] [1 1]
Epoch 40
0.61582243
(1.0, 1.0)
[1 1] [1 1]
Epoch 60
0.35755304
(1.0, 1.0)
[1 1] [1 1]
Epoch 80
0.20687109
(1.0, 1.0)
[1 1] [1 1]
Epoch 100
0.12050087
(1.0, 1.0)
[1 1] [1 1]
Epoch 120
0.07233672
(1.0, 1.0)
[1 1] [1 1]
Epoch 140
0.044242017
(1.0, 1.0)
[1 1] [1 3]
Epoch 160
0.027990473
(0.25, 0.3333333333333333)
[1 1] [3 1]
Epoch 180
0.018684551
(0.25, 0.3333333333333333)

Max UAR:1.0 at epoch 40
Max UF1:1.0 at epoch 40
Test 33


[1 6 6 3 6 6 6] [4 1 4 4 4 4 4]
Epoch 0
1.953525
(0.0, 0.0)
[3 6 6 6 6 6 1] [2 6 1 5 5 1 5]
Epoch 20
1.0705693
(0.04, 0.06666666666666668)
[6 6 6 6 1 3 6] [1 1 5 6 2 4 6]
Epoch 40
0.60843986
(0.06666666666666667, 0.09523809523809525)
[6 6 6 1 6 3 6] [6 6 1 2 1 4 5]
Epoch 60
0.3481791
(0.06666666666666667, 0.09523809523809525)
[3 6 6 6 6 1 6] [4 6 6 1 1 2 5]
Epoch 80
0.2009434
(0.06666666666666667, 0.09523809523809525)
[6 6 6 6 3 1 6] [1 4 6 6 4 6 5]
Epoch 100
0.11925825
(0.08, 0.1)
[1 6 6 6 3 6 6] [6 6 4 5 4 6 1]
Epoch 120
0.07324129
(0.08, 0.1)
[6 6 6 1 6 3 6] [5 1 6 6 6 4 4]
Epoch 140
0.045541484
(0.08, 0.1)
[3 6 6 6 6 1 6] [1 6 5 1 4 6 6]
Epoch 160
0.029076979
(0.08, 0.1)
[1 6 6 6 6 3 6] [6 1 5 6 6 1 4]
Epoch 180
0.019450782
(0.08, 0.1)

Max UAR:0.08 at epoch 100
Max UF1:0.1 at epoch 100
Test 34


[6 1 6 3] [4 4 4 4]
Epoch 0
1.9532512
(0.0, 0.0)
[6 1 6 3] [4 5 6 4]
Epoch 20
1.0617716
(0.1, 0.13333333333333333)
[1 6 6 3] [3 3 6 0]
Epoch 40
0.6020062
(0.125, 0.16666666666666666)
[1 6 6 3] [3 3 6 0]
Epoch 60
0.34898347
(0.125, 0.16666666666666666)
[3 6 1 6] [4 3 6 6]
Epoch 80
0.20201565
(0.125, 0.125)
[6 3 1 6] [6 4 6 3]
Epoch 100
0.1168924
(0.125, 0.125)
[6 1 6 3] [3 6 6 4]
Epoch 120
0.069703914
(0.125, 0.125)
[3 1 6 6] [4 6 6 6]
Epoch 140
0.042682268
(0.25, 0.2)
[3 6 1 6] [4 6 6 6]
Epoch 160
0.02710518
(0.25, 0.2)
[6 1 6 3] [6 6 6 4]
Epoch 180
0.01818363
(0.25, 0.2)

Max UAR:0.25 at epoch 140
Max UF1:0.2 at epoch 140
Test 35


[1 1 1 1 1] [4 4 4 4 4]
Epoch 0
1.9527428
(0.0, 0.0)
[1 1 1 1 1] [1 4 1 1 1]
Epoch 20
1.070467
(0.4, 0.4444444444444445)
[1 1 1 1 1] [1 1 1 1 4]
Epoch 40
0.61516595
(0.4, 0.4444444444444445)
[1 1 1 1 1] [1 1 1 1 1]
Epoch 60
0.3577134
(1.0, 1.0)
[1 1 1 1 1] [1 1 1 1 1]
Epoch 80
0.20738135
(1.0, 1.0)
[1 1 1 1 1] [1 1 1 1 1]
Epoch 100
0.121117905
(1.0, 1.0)
[1 1 1 1 1] [1 1 1 1 1]
Epoch 120
0.07300425
(1.0, 1.0)
[1 1 1 1 1] [1 1 1 1 1]
Epoch 140
0.04489285
(1.0, 1.0)
[1 1 1 1 1] [1 1 1 1 1]
Epoch 160
0.028597586
(1.0, 1.0)
[1 1 1 1 1] [1 1 1 1 1]
Epoch 180
0.01914234
(1.0, 1.0)

Max UAR:1.0 at epoch 60
Max UF1:1.0 at epoch 60
Test 36


[4] [4]
Epoch 0
1.9521959
(1.0, 1.0)
[4] [4]
Epoch 20
1.0670071
(1.0, 1.0)
[4] [4]
Epoch 40
0.6120634
(1.0, 1.0)
[4] [4]
Epoch 60
0.3545702
(1.0, 1.0)
[4] [4]
Epoch 80
0.20461099
(1.0, 1.0)
[4] [4]
Epoch 100
0.11913281
(1.0, 1.0)
[4] [4]
Epoch 120
0.07174634
(1.0, 1.0)
[4] [4]
Epoch 140
0.044235013
(1.0, 1.0)
[4] [4]
Epoch 160
0.028181044
(1.0, 1.0)
[4] [4]
Epoch 180
0.018861346
(1.0, 1.0)

Max UAR:1.0 at epoch 0
Max UF1:1.0 at epoch 0
Test 37


[4 3 4 3 3 4 3 4 3 4 2] [4 4 4 6 6 1 1 4 6 6 6]
Epoch 0
1.9487826
(0.12, 0.1333333333333333)
[3 3 3 3 4 4 4 2 4 3 4] [6 1 4 3 1 4 4 1 4 3 1]
Epoch 20
1.0714341
(0.2, 0.24761904761904763)
[3 4 3 2 3 4 4 4 3 4 3] [1 4 6 3 4 1 4 4 4 1 3]
Epoch 40
0.6179647
(0.16, 0.17714285714285713)
[4 4 4 3 3 4 4 3 2 3 3] [4 1 4 1 6 4 1 3 2 3 4]
Epoch 60
0.35569274
(0.4, 0.44761904761904764)
[3 4 2 3 4 3 3 4 4 3 4] [6 1 2 3 4 3 1 1 4 4 4]
Epoch 80
0.2024523
(0.4, 0.44761904761904764)
[3 4 3 4 4 3 3 2 4 4 3] [3 1 6 4 4 4 3 2 1 1 1]
Epoch 100
0.11645364
(0.36, 0.4142857142857143)
[4 3 4 3 2 3 4 4 3 4 3] [1 6 4 1 2 3 1 3 4 1 6]
Epoch 120
0.06911056
(0.27999999999999997, 0.31428571428571433)
[4 4 4 3 3 3 4 2 3 4 3] [1 3 1 6 4 6 1 2 1 4 4]
Epoch 140
0.04212376
(0.24, 0.25)
[3 2 4 3 3 4 4 4 4 3 3] [1 2 1 6 6 3 4 1 1 4 4]
Epoch 160
0.026780227
(0.24, 0.25)
[3 4 4 3 4 4 3 3 3 4 2] [4 4 1 4 1 4 6 6 1 1 2]
Epoch 180
0.018017564
(0.27999999999999997, 0.28888888888888886)

Max UAR:0.4 at epoch 60
Max UF1:0.44761904

[2] [4]
Epoch 0
1.9508082
(0.0, 0.0)
[2] [4]
Epoch 20
1.0795808
(0.0, 0.0)
[2] [2]
Epoch 40
0.624872
(1.0, 1.0)
[2] [2]
Epoch 60
0.36422002
(1.0, 1.0)
[2] [4]
Epoch 80
0.21085322
(0.0, 0.0)
[2] [4]
Epoch 100
0.1222787
(0.0, 0.0)
[2] [4]
Epoch 120
0.073474996
(0.0, 0.0)
[2] [4]
Epoch 140
0.045245852
(0.0, 0.0)
[2] [4]
Epoch 160
0.028856127
(0.0, 0.0)
[2] [4]
Epoch 180
0.019366445
(0.0, 0.0)

Max UAR:1.0 at epoch 40
Max UF1:1.0 at epoch 40
Test 39


[1 1 1 1] [6 4 4 4]
Epoch 0
1.952641
(0.0, 0.0)
[1 1 1 1] [3 1 1 4]
Epoch 20
1.0668753
(0.16666666666666666, 0.2222222222222222)
[1 1 1 1] [3 1 1 0]
Epoch 40
0.6177256
(0.16666666666666666, 0.2222222222222222)
[1 1 1 1] [1 3 1 3]
Epoch 60
0.36237937
(0.25, 0.3333333333333333)
[1 1 1 1] [1 3 3 1]
Epoch 80
0.21046972
(0.25, 0.3333333333333333)
[1 1 1 1] [1 3 1 1]
Epoch 100
0.12226081
(0.375, 0.42857142857142855)
[1 1 1 1] [1 1 1 3]
Epoch 120
0.07349448
(0.375, 0.42857142857142855)
[1 1 1 1] [1 1 1 3]
Epoch 140
0.0452981
(0.375, 0.42857142857142855)
[1 1 1 1] [3 1 1 1]
Epoch 160
0.028794277
(0.375, 0.42857142857142855)
[1 1 1 1] [1 1 3 1]
Epoch 180
0.01926641
(0.375, 0.42857142857142855)

Max UAR:0.375 at epoch 100
Max UF1:0.42857142857142855 at epoch 100
Test 40


[3 6 1 6 6 1 1 6 1 3 1] [4 4 1 4 4 4 4 4 4 4 4]
Epoch 0
1.9533031
(0.05, 0.08333333333333334)
[1 3 1 6 1 6 3 6 1 1 6] [5 4 1 5 1 5 2 5 1 1 6]
Epoch 20
1.0617722
(0.17500000000000002, 0.21481481481481482)
[6 6 1 1 3 1 6 1 1 6 3] [5 5 1 1 3 0 5 5 1 6 3]
Epoch 40
0.6061124
(0.37, 0.43)
[1 1 1 6 3 3 1 6 6 6 1] [1 6 1 6 3 1 5 6 5 6 1]
Epoch 60
0.3518215
(0.4625, 0.5208333333333333)
[1 6 1 3 6 1 3 1 6 6 1] [5 6 1 3 5 1 1 1 6 6 6]
Epoch 80
0.20578349
(0.4625, 0.5208333333333333)
[1 6 1 1 1 3 6 1 6 6 3] [1 5 1 1 1 1 6 6 6 6 3]
Epoch 100
0.12119422
(0.5125, 0.5541666666666667)
[1 3 1 1 3 6 1 6 6 1 6] [0 1 1 1 3 6 1 6 6 1 5]
Epoch 120
0.07369021
(0.41, 0.4647619047619048)
[1 3 6 6 6 1 6 1 1 3 1] [1 3 6 5 6 1 6 1 1 4 0]
Epoch 140
0.04591006
(0.3416666666666666, 0.4021164021164021)
[1 1 6 1 6 3 6 3 6 1 1] [1 1 6 1 6 4 5 3 6 0 1]
Epoch 160
0.029364588
(0.3416666666666666, 0.4021164021164021)
[1 6 1 6 1 6 3 1 6 3 1] [1 6 1 5 1 6 3 0 6 4 1]
Epoch 180
0.019538682
(0.3416666666666666, 0.402116402116402

[3 3] [6 4]
Epoch 0
1.9524082
(0.0, 0.0)
[3 3] [1 3]
Epoch 20
1.0718663
(0.25, 0.3333333333333333)
[3 3] [2 3]
Epoch 40
0.61557776
(0.25, 0.3333333333333333)
[3 3] [2 3]
Epoch 60
0.35754418
(0.25, 0.3333333333333333)
[3 3] [3 2]
Epoch 80
0.20779264
(0.25, 0.3333333333333333)
[3 3] [1 3]
Epoch 100
0.121641405
(0.25, 0.3333333333333333)
[3 3] [3 1]
Epoch 120
0.07358987
(0.25, 0.3333333333333333)
[3 3] [1 1]
Epoch 140
0.04565691
(0.0, 0.0)
[3 3] [1 1]
Epoch 160
0.02919854
(0.0, 0.0)
[3 3] [1 1]
Epoch 180
0.019630913
(0.0, 0.0)

Max UAR:0.25 at epoch 20
Max UF1:0.3333333333333333 at epoch 20
Test 42


[3 3 3] [4 3 6]
Epoch 0
1.952452
(0.1111111111111111, 0.16666666666666666)
[3 3 3] [3 0 3]
Epoch 20
1.073988
(0.3333333333333333, 0.4)
[3 3 3] [3 3 4]
Epoch 40
0.6181216
(0.3333333333333333, 0.4)
[3 3 3] [4 3 1]
Epoch 60
0.36008462
(0.1111111111111111, 0.16666666666666666)
[3 3 3] [3 1 4]
Epoch 80
0.20926812
(0.1111111111111111, 0.16666666666666666)
[3 3 3] [4 3 1]
Epoch 100
0.12250889
(0.1111111111111111, 0.16666666666666666)
[3 3 3] [4 3 1]
Epoch 120
0.07425705
(0.1111111111111111, 0.16666666666666666)
[3 3 3] [3 4 1]
Epoch 140
0.04606764
(0.1111111111111111, 0.16666666666666666)
[3 3 3] [4 3 1]
Epoch 160
0.029439978
(0.1111111111111111, 0.16666666666666666)
[3 3 3] [1 4 1]
Epoch 180
0.019706758
(0.0, 0.0)

Max UAR:0.3333333333333333 at epoch 20
Max UF1:0.4 at epoch 20
Test 43


[3 6 1] [4 4 1]
Epoch 0
1.95276
(0.25, 0.25)
[1 3 6] [1 5 6]
Epoch 20
1.0718559
(0.5, 0.5)
[6 1 3] [6 1 3]
Epoch 40
0.6139969
(1.0, 1.0)
[3 6 1] [4 6 1]
Epoch 60
0.35468218
(0.5, 0.5)
[6 3 1] [6 4 1]
Epoch 80
0.20399392
(0.5, 0.5)
[1 6 3] [3 6 4]
Epoch 100
0.11848321
(0.25, 0.25)
[1 3 6] [3 4 6]
Epoch 120
0.071527064
(0.25, 0.25)
[3 1 6] [4 3 6]
Epoch 140
0.0441892
(0.25, 0.25)
[6 1 3] [6 1 4]
Epoch 160
0.028256524
(0.5, 0.5)
[6 3 1] [6 4 1]
Epoch 180
0.019046238
(0.5, 0.5)

Max UAR:1.0 at epoch 40
Max UF1:1.0 at epoch 40
Test 44


[4 3 3] [4 4 4]
Epoch 0
1.9518741
(0.5, 0.25)
[3 4 3] [1 2 6]
Epoch 20
1.0680219
(0.0, 0.0)
[4 3 3] [2 3 3]
Epoch 40
0.6128817
(0.3333333333333333, 0.3333333333333333)
[3 3 4] [3 3 2]
Epoch 60
0.35639226
(0.3333333333333333, 0.3333333333333333)
[3 3 4] [3 3 3]
Epoch 80
0.20704351
(0.5, 0.4)
[3 3 4] [3 3 3]
Epoch 100
0.121007994
(0.5, 0.4)
[3 4 3] [3 1 3]
Epoch 120
0.07270875
(0.3333333333333333, 0.3333333333333333)
[3 3 4] [3 3 1]
Epoch 140
0.044439416
(0.3333333333333333, 0.3333333333333333)
[4 3 3] [1 3 3]
Epoch 160
0.028097646
(0.3333333333333333, 0.3333333333333333)
[3 3 4] [3 3 1]
Epoch 180
0.018741632
(0.3333333333333333, 0.3333333333333333)

Max UAR:0.5 at epoch 0
Max UF1:0.4 at epoch 80
Test 45


[3 4 3 4 1 4 4 3 5 1 4 1 4 5 4 3 3 1 1 3 1 1 1 1 4 1 3 1 1 1 4 1 6] [4 6 6 4 3 4 4 4 4 4 6 4 4 4 1 4 6 4 4 4 1 1 6 4 4 6 4 6 6 1 4 6 4]
Epoch 0
1.9552587
(0.17619047619047618, 0.15238095238095237)
[3 1 3 3 3 5 4 4 1 1 4 1 1 1 4 5 1 4 1 3 1 4 1 1 4 1 4 3 4 6 3 1 1] [3 1 4 5 4 6 4 4 1 1 4 1 1 1 3 6 1 4 1 1 1 4 1 1 4 1 4 6 1 6 4 1 1]
Epoch 20
1.0614153
(0.584126984126984, 0.45847953216374265)
[3 5 1 4 4 5 4 1 1 4 1 3 3 3 1 4 1 4 1 1 1 1 6 1 3 4 3 1 4 3 1 4 1] [3 6 1 4 2 6 4 1 1 4 1 4 4 6 1 4 1 4 1 1 3 1 6 1 1 4 5 1 1 3 1 4 1]
Epoch 40
0.60736114
(0.49867724867724866, 0.4123882503192848)
[1 3 5 4 5 4 3 1 1 1 1 1 4 1 3 4 4 1 1 4 4 1 3 3 1 1 1 4 4 1 6 3 3] [1 5 6 4 1 4 3 1 1 1 1 1 4 3 6 4 4 1 1 4 2 1 3 1 1 1 1 4 1 1 6 4 4]
Epoch 60
0.3536629
(0.49867724867724866, 0.42407407407407405)
[3 1 4 3 4 4 1 6 1 1 4 5 1 4 4 1 3 4 1 1 4 1 1 4 1 1 3 3 5 1 1 3 3] [6 3 1 5 4 1 1 6 1 1 4 1 1 4 4 1 3 4 1 1 2 1 1 4 1 1 3 4 6 1 1 1 4]
Epoch 80
0.20442663
(0.4801587301587302, 0.4074320050600886)
[4 1 3 3 3 1 6

[1 6 3 1 6 6 6 1 3 5 3 6] [4 4 0 4 4 4 4 4 4 4 4 4]
Epoch 0
1.955559
(0.0, 0.0)
[3 6 6 1 3 6 3 5 1 6 6 1] [5 3 5 1 4 4 6 6 2 4 6 1]
Epoch 20
1.0614712
(0.14444444444444446, 0.17500000000000002)
[3 3 5 1 6 6 6 6 6 1 3 1] [6 5 6 4 6 3 4 6 6 1 4 1]
Epoch 40
0.60479146
(0.2533333333333333, 0.27999999999999997)
[6 3 6 1 1 3 6 6 6 1 5 3] [4 5 3 1 1 6 6 6 4 1 6 3]
Epoch 60
0.35132658
(0.3466666666666667, 0.3688888888888889)
[6 1 6 1 6 5 3 3 1 6 3 6] [1 1 6 1 6 6 5 3 1 3 6 6]
Epoch 80
0.20582399
(0.4833333333333333, 0.4642857142857143)
[1 6 1 6 5 3 3 6 1 6 6 3] [1 6 1 6 6 6 5 6 1 1 6 3]
Epoch 100
0.121196076
(0.5333333333333333, 0.5211038961038961)
[5 1 6 3 3 6 6 1 1 6 6 3] [6 1 1 5 6 6 6 1 1 6 6 3]
Epoch 120
0.073911
(0.5333333333333333, 0.5211038961038961)
[6 6 6 6 1 5 1 3 1 3 3 6] [6 6 6 6 1 6 1 5 1 3 6 1]
Epoch 140
0.04624469
(0.5333333333333333, 0.5211038961038961)
[3 1 3 3 6 6 6 6 5 6 1 1] [5 1 6 3 6 6 6 6 6 1 1 1]
Epoch 160
0.029855521
(0.5333333333333333, 0.5211038961038961)
[3 6 3 6 3

[1 1] [4 4]
Epoch 0
1.952576
(0.0, 0.0)
[1 1] [4 5]
Epoch 20
1.0663218
(0.0, 0.0)
[1 1] [6 4]
Epoch 40
0.61113393
(0.0, 0.0)
[1 1] [6 4]
Epoch 60
0.3540369
(0.0, 0.0)
[1 1] [4 4]
Epoch 80
0.20356269
(0.0, 0.0)
[1 1] [4 4]
Epoch 100
0.117186986
(0.0, 0.0)
[1 1] [4 1]
Epoch 120
0.06999826
(0.25, 0.3333333333333333)
[1 1] [4 1]
Epoch 140
0.043135386
(0.25, 0.3333333333333333)
[1 1] [4 1]
Epoch 160
0.027662735
(0.25, 0.3333333333333333)
[1 1] [4 1]
Epoch 180
0.018745914
(0.25, 0.3333333333333333)

Max UAR:0.25 at epoch 120
Max UF1:0.3333333333333333 at epoch 120
Test 48


[4] [4]
Epoch 0
1.9521618
(1.0, 1.0)
[4] [3]
Epoch 20
1.0666254
(0.0, 0.0)
[4] [3]
Epoch 40
0.6093423
(0.0, 0.0)
[4] [3]
Epoch 60
0.35132575
(0.0, 0.0)
[4] [3]
Epoch 80
0.20286167
(0.0, 0.0)
[4] [3]
Epoch 100
0.11886116
(0.0, 0.0)
[4] [3]
Epoch 120
0.07227706
(0.0, 0.0)
[4] [3]
Epoch 140
0.044961445
(0.0, 0.0)
[4] [3]
Epoch 160
0.028896647
(0.0, 0.0)
[4] [3]
Epoch 180
0.019517114
(0.0, 0.0)

Max UAR:1.0 at epoch 0
Max UF1:1.0 at epoch 0
Test 49


[4 4] [4 1]
Epoch 0
1.9515625
(0.25, 0.3333333333333333)
[4 4] [4 4]
Epoch 20
1.0728916
(1.0, 1.0)
[4 4] [4 4]
Epoch 40
0.61211675
(1.0, 1.0)
[4 4] [4 4]
Epoch 60
0.3542165
(1.0, 1.0)
[4 4] [4 4]
Epoch 80
0.2048003
(1.0, 1.0)
[4 4] [4 4]
Epoch 100
0.11948606
(1.0, 1.0)
[4 4] [4 4]
Epoch 120
0.07206218
(1.0, 1.0)
[4 4] [4 4]
Epoch 140
0.044505388
(1.0, 1.0)
[4 4] [4 4]
Epoch 160
0.028408274
(1.0, 1.0)
[4 4] [4 4]
Epoch 180
0.01907281
(1.0, 1.0)

Max UAR:1.0 at epoch 20
Max UF1:1.0 at epoch 20
Test 50


[4 1 1 4 3 1 1 4] [1 4 6 4 4 4 4 6]
Epoch 0
1.953633
(0.08333333333333333, 0.0625)
[4 1 1 1 4 4 1 3] [1 1 1 1 1 3 1 4]
Epoch 20
1.0694902
(0.3333333333333333, 0.26666666666666666)
[3 4 4 1 4 1 1 1] [1 3 1 1 1 1 1 1]
Epoch 40
0.6121058
(0.3333333333333333, 0.24242424242424243)
[1 4 4 1 1 4 3 1] [1 1 3 1 1 1 4 1]
Epoch 60
0.35582688
(0.3333333333333333, 0.26666666666666666)
[3 4 1 4 1 1 1 4] [4 3 1 4 1 1 1 1]
Epoch 80
0.20594524
(0.4444444444444444, 0.42962962962962964)
[1 1 1 1 4 4 4 3] [1 1 1 1 3 1 4 4]
Epoch 100
0.120399676
(0.4444444444444444, 0.42962962962962964)
[4 1 3 4 1 1 4 1] [3 1 4 4 1 1 1 1]
Epoch 120
0.0727131
(0.4444444444444444, 0.42962962962962964)
[1 4 1 1 3 4 1 4] [1 4 1 1 4 3 1 1]
Epoch 140
0.044850502
(0.4444444444444444, 0.42962962962962964)
[1 1 3 1 4 4 1 4] [1 1 4 1 4 3 1 1]
Epoch 160
0.02854599
(0.4444444444444444, 0.42962962962962964)
[4 4 1 1 1 3 1 4] [1 3 1 1 1 4 1 4]
Epoch 180
0.019113706
(0.4444444444444444, 0.42962962962962964)

Max UAR:0.4444444444444444 at

[1 6 6 1 6 6] [4 4 1 4 4 4]
Epoch 0
1.9536514
(0.0, 0.0)
[6 1 6 6 6 1] [6 4 4 1 4 3]
Epoch 20
1.0650655
(0.0625, 0.1)
[1 6 6 6 1 6] [3 6 1 6 4 4]
Epoch 40
0.6010424
(0.125, 0.16666666666666666)
[6 1 1 6 6 6] [1 1 3 6 6 4]
Epoch 60
0.34386048
(0.25, 0.29166666666666663)
[6 6 6 1 1 6] [1 6 3 3 1 4]
Epoch 80
0.19954842
(0.1875, 0.225)
[6 6 6 6 1 1] [6 3 4 1 3 1]
Epoch 100
0.11725458
(0.1875, 0.225)
[6 6 1 1 6 6] [4 6 3 1 1 3]
Epoch 120
0.07060083
(0.1875, 0.225)
[6 6 6 6 1 1] [1 6 4 3 1 3]
Epoch 140
0.043586813
(0.1875, 0.225)
[6 1 1 6 6 6] [6 1 3 1 4 3]
Epoch 160
0.027908126
(0.1875, 0.225)
[6 6 1 6 6 1] [4 1 1 6 3 3]
Epoch 180
0.01884133
(0.1875, 0.225)

Max UAR:0.25 at epoch 60
Max UF1:0.29166666666666663 at epoch 60
Test 52


[6 1 1 6 1] [4 4 4 4 4]
Epoch 0
1.9525872
(0.0, 0.0)
[1 6 1 1 6] [6 6 5 1 6]
Epoch 20
1.0677569
(0.4444444444444444, 0.43333333333333335)
[1 6 6 1 1] [6 6 6 6 1]
Epoch 40
0.610593
(0.6666666666666666, 0.5833333333333333)
[1 6 6 1 1] [1 6 6 6 6]
Epoch 60
0.35213664
(0.6666666666666666, 0.5833333333333333)
[1 1 1 6 6] [1 6 1 6 6]
Epoch 80
0.20291641
(0.8333333333333333, 0.8)
[1 6 6 1 1] [1 6 6 6 3]
Epoch 100
0.11872127
(0.4444444444444444, 0.43333333333333335)
[1 6 1 6 1] [3 6 1 6 6]
Epoch 120
0.0721554
(0.4444444444444444, 0.43333333333333335)
[1 6 1 1 6] [1 6 6 3 6]
Epoch 140
0.044680562
(0.4444444444444444, 0.43333333333333335)
[1 1 6 6 1] [3 1 6 6 6]
Epoch 160
0.028505962
(0.4444444444444444, 0.43333333333333335)
[1 6 1 6 1] [3 6 6 6 1]
Epoch 180
0.019098286
(0.4444444444444444, 0.43333333333333335)

Max UAR:0.8333333333333333 at epoch 80
Max UF1:0.8 at epoch 80
Test 53


[1 5 3 1 1 1 1 1 3 1 1 1] [4 6 4 4 4 6 4 4 4 4 6 4]
Epoch 0
1.9542766
(0.0, 0.0)
[1 1 5 3 1 1 1 1 1 1 1 3] [0 1 6 5 1 1 4 1 1 6 1 1]
Epoch 20
1.0732961
(0.1111111111111111, 0.125)
[1 1 1 5 3 1 3 1 1 1 1 1] [1 1 1 6 1 3 5 1 1 1 1 4]
Epoch 40
0.615895
(0.15555555555555556, 0.1647058823529412)
[1 1 5 1 1 1 1 1 3 1 1 3] [1 1 2 1 1 1 1 3 1 1 1 3]
Epoch 60
0.35692102
(0.3472222222222222, 0.3472222222222222)
[1 3 5 1 3 1 1 1 1 1 1 1] [1 3 2 3 1 1 1 1 1 1 1 1]
Epoch 80
0.2084268
(0.3472222222222222, 0.3472222222222222)
[1 3 1 1 1 1 1 3 1 5 1 1] [1 3 3 1 1 1 1 1 1 2 3 1]
Epoch 100
0.12320489
(0.3194444444444444, 0.3058823529411765)
[1 1 3 3 1 1 1 5 1 1 1 1] [3 1 3 1 1 3 1 2 1 1 1 1]
Epoch 120
0.07486686
(0.3194444444444444, 0.3058823529411765)
[3 1 1 1 1 1 1 5 3 1 1 1] [1 1 3 1 1 3 1 2 3 1 1 1]
Epoch 140
0.046431363
(0.3194444444444444, 0.3058823529411765)
[5 3 1 1 1 1 3 1 1 1 1 1] [2 1 1 3 1 1 3 3 1 1 1 3]
Epoch 160
0.029643012
(0.29166666666666663, 0.2708333333333333)
[1 5 1 3 1 1 1 1 3 1 1 1

NameError: name 'train_process_filename' is not defined